name: "🐛 BUG REPORT"
description: "Thanks for submitting a bug report, this helps our indie team to improve our catalog of Games!"
title: "[Bug]: "
labels:
  - "bug"

body:
  - type: "dropdown"
    id: "game-selection"
    attributes:
      label: "Game:"
      options:
        - "Murkmask - Horror Escape"
        - "Murkmask - Academy Outbreak"
        - "Murkmask 3"
    validations:
      required: true

  - type: "dropdown"
    id: "operating-system"
    attributes:
      label: "Operating System:"
      options:
        - "Android"
        - "Windows"
        - "Linux"
        - "MacOS"
    validations:
      required: true

  - type: "textarea"
    id: "bug-description"
    attributes:
      label: "Bug Description:"
      placeholder: "Describe what went wrong..."
    validations:
      required: true

  - type: "textarea"
    id: "steps-to-rediscover"
    attributes:
      label: "Steps to Rediscover Glitch:"
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: "input"
    id: "game-version"
    attributes:
      label: "Game Version:"
      placeholder: "e.g., 1.0.4"
    validations:
      required: true
      regex: "^[0-9.]+$"

  - type: "checkboxes"
    id: "configuration-checks"
    attributes:
      label: "Additional Information"
      options:
        - label: "I'm on the Latest Version"
          required: false
        - label: "Debug Build"
          required: false

  - type: "checkboxes"
    id: "rules-agreement"
    attributes:
      label: "Guidelines Agreement"
      options:
        - label: "I have read the rules and agree that i have cross-checked all issues to confirm if a similar report exists."
          required: true
